/-
File: signature_recover_public_key_get_generator_point_soundness.lean

Autogenerated file.
-/
import starkware.cairo.lean.semantics.soundness.hoare
import .signature_recover_public_key_code
import ..signature_recover_public_key_spec
open tactic

open starkware.cairo.common.cairo_secp.signature
open starkware.cairo.common.cairo_secp.bigint3
open starkware.cairo.common.cairo_secp.ec_point

variables {F : Type} [field F] [decidable_eq F] [prelude_hyps F]
variable  mem : F → F
variable  σ : register_state F

/- starkware.cairo.common.cairo_secp.signature.get_generator_point autogenerated soundness theorem -/

theorem auto_sound_get_generator_point
    -- code is in memory at σ.pc
    (h_mem : mem_at mem code_get_generator_point σ.pc)
    -- input arguments on the stack
    -- conclusion
  : ensures_ret mem σ (λ κ τ, τ.ap = σ.ap + 6 ∧ spec_get_generator_point mem κ (cast_EcPoint  mem (τ.ap - 6))) :=
begin
  apply ensures_of_ensuresb, intro νbound,
  have h_mem_rec := h_mem,
  unpack_memory code_get_generator_point at h_mem with ⟨hpc0, hpc1, hpc2, hpc3, hpc4, hpc5, hpc6, hpc7, hpc8, hpc9, hpc10, hpc11, hpc12⟩,
  -- return
  step_assert_eq hpc0 hpc1 with hret0,
  step_assert_eq hpc2 hpc3 with hret1,
  step_assert_eq hpc4 hpc5 with hret2,
  step_assert_eq hpc6 hpc7 with hret3,
  step_assert_eq hpc8 hpc9 with hret4,
  step_assert_eq hpc10 hpc11 with hret5,
  step_ret hpc12,
  -- finish
  step_done, use_only [rfl, rfl],
  split, refl,
  -- Final Proof
  -- user-provided reduction
  suffices auto_spec: auto_spec_get_generator_point mem _  _,
  { apply sound_get_generator_point, apply auto_spec },
  -- prove the auto generated assertion
  dsimp [auto_spec_get_generator_point],
  try { norm_num1 }, try { arith_simps },
  try { split, trivial <|> linarith },
  try { ensures_simps; try { simp only [add_neg_eq_sub] }, },
  try { dsimp [cast_EcPoint, cast_BigInt3] },
  try { arith_simps }, try { simp only [hret0, hret1, hret2, hret3, hret4, hret5] },
  try { arith_simps; try { split }; triv <|> refl <|> simp <|> abel; try { norm_num } },
end

