/-
  Specifications file for signature_recover_public_key_spec.cairo

  Do not modify the constant definitions, structure definitions, or automatic specifications.
  Do not change the name or arguments of the user specifications and soundness theorems.

  You may freely move the definitions around in the file.
  You may add definitions and theorems wherever you wish in this file.
-/
import starkware.cairo.lean.semantics.soundness.prelude
import starkware.cairo.common.cairo_secp.ec_spec
import starkware.cairo.common.cairo_secp.signature_spec
import starkware.cairo.common.cairo_secp.bigint_spec
import starkware.cairo.common.cairo_secp.field_spec
import starkware.cairo.common.math_spec

import starkware.cairo.common.cairo_secp.bigint3_spec
import starkware.cairo.common.cairo_secp.ec_point_spec

open starkware.cairo.common.cairo_secp.bigint3
open starkware.cairo.common.cairo_secp.ec_point
open starkware.cairo.common.cairo_secp.ec
open starkware.cairo.common.cairo_secp.signature
open starkware.cairo.common.cairo_secp.bigint
open starkware.cairo.common.cairo_secp.field
open starkware.cairo.common.math

namespace starkware.cairo.common.cairo_secp.verification.signature_recover_public_key

variables {F : Type} [field F] [decidable_eq F] [prelude_hyps F]

-- End of automatically generated prelude.

/-
-- Function: call_recover_public_key
-/

/- call_recover_public_key autogenerated specification -/

-- Do not change this definition.
def auto_spec_call_recover_public_key (mem : F → F) (κ : ℕ) (range_check_ptr : F) (msg_hash r s : BigInt3 mem) (v ρ_range_check_ptr : F) (ρ_public_key_point : EcPoint mem) : Prop :=
  ∃ (κ₁ : ℕ), spec_recover_public_key mem κ₁ range_check_ptr msg_hash r s v ρ_range_check_ptr ρ_public_key_point ∧
  κ₁ + 13 ≤ κ

-- You may change anything in this definition except the name and arguments.
def spec_call_recover_public_key (mem : F → F) (κ : ℕ) (range_check_ptr : F) (msg_hash r s : BigInt3 mem) (v ρ_range_check_ptr : F) (ρ_public_key_point : EcPoint mem) : Prop :=
  auto_spec_call_recover_public_key mem κ range_check_ptr msg_hash r s v ρ_range_check_ptr ρ_public_key_point

/- call_recover_public_key soundness theorem -/

-- Do not change the statement of this theorem. You may change the proof.
theorem sound_call_recover_public_key
    {mem : F → F}
    (κ : ℕ)
    (range_check_ptr : F) (msg_hash r s : BigInt3 mem) (v ρ_range_check_ptr : F) (ρ_public_key_point : EcPoint mem)
    (h_auto : auto_spec_call_recover_public_key mem κ range_check_ptr msg_hash r s v ρ_range_check_ptr ρ_public_key_point) :
  spec_call_recover_public_key mem κ range_check_ptr msg_hash r s v ρ_range_check_ptr ρ_public_key_point :=
begin
  exact h_auto
end


end starkware.cairo.common.cairo_secp.verification.signature_recover_public_key
